source_type: "gcs" # Switch between "gcs" or "gsheet", or "bigquery"

gcs:
  bucket_name: "aspect-application-poc-bucket"
  file_prefix: "vz_kc" # Looks for file_prefix_*_DD_MM_YYYY.csv

gsheets:
  url: ""
  user_email: "shivjeet.dyade@onixnet.com"

bigquery:
  output:
    project: "vz-it-np-keiv-dev-dpev-0"
    dataset: "gcp_governance_tbls"
    table: "governance_aspect_details_hist"
  input:
    project: "vz-it-np-keiv-dev-dpev-0"
    dataset: "gcp_governance_tbls"
    table: "governance_aspect_details_stg_v"

dataplex:
  api_retry_total: 3
  backoff_factor: 1
